#!/bin/bash
# Casa Cactus Buenavista — Complete Image Rename Script
# Run from: /localghost/web/public/images/temp/
# Usage: bash rename-images.sh

set -e
cd "$(dirname "$0")"

echo "Renaming Casa Cactus images..."

# ── DSCF SERIES ──────────────────────────────────────────────────────────────
mv "DSCF3402.jpg"  "entrance-sign-doorbell-wooden-white-wall.jpg"
mv "DSCF3407.jpg"  "hero-garden-swing-pool-reflection-woman-yellow-dress.jpg"
mv "DSCF3408.jpg"  "pool-reflections-palm-shadows.jpg"
mv "DSCF3409.jpg"  "garden-trees-canopy-blue-sky.jpg"
mv "DSCF3418.jpg"  "garden-red-ginger-flowers-tropical.jpg"
mv "DSCF3420.jpg"  "garden-large-leaf-texture-close-up.jpg"
mv "DSCF3421.jpg"  "bungalow-terrace-lounge-chairs-hammock-palapa.jpg"
mv "DSCF3429.jpg"  "garden-bird-yellow-breast-tree-branch.jpg"
mv "DSCF3442.jpg"  "garden-dark-palm-fronds-jungle.jpg"
mv "DSCF3479.jpg"  "village-buenavista-street-cocacola-wall.jpg"

# ── DJI DRONE SERIES ─────────────────────────────────────────────────────────
mv "DJI_20241113100441_0003_D.jpg"  "aerial-pool-garden-overhead-woman-floating.jpg"
mv "DJI_20241113100936_0014_D.jpg"  "aerial-pool-steps-woman-sitting.jpg"
mv "DJI_20241113101624_0025_D.jpg"  "aerial-pool-full-view-garden.jpg"
mv "DJI_20241113111631_0034_D.jpg"  "lagoon-sailboat-open-water-aerial.jpg"
mv "DJI_20241113111736_0036_D.jpg"  "lagoon-sailboat-green-jungle-banks-aerial.jpg"

# ── LOCATION SERIES ──────────────────────────────────────────────────────────
mv "LOCATION-02.jpg"  "aerial-buenavista-village-lagoon-pin-wider.jpg"
mv "LOCATION-03.jpg"  "aerial-buenavista-village-lagoon-pin.jpg"

# ── CASA CACTUS 2025 SERIES ──────────────────────────────────────────────────
mv "CASA CACTUS2025-001.jpg"  "room-detail-alarm-clock-crochet-cactus-wifi-desk.jpg"
mv "CASA CACTUS2025-002.jpg"  "room-detail-crochet-cactus-alarm-clock-floor-window.jpg"
mv "CASA CACTUS2025-003.jpg"  "bathroom-shower-head-chrome-close-up.jpg"
mv "CASA CACTUS2025-004.jpg"  "bungalow-exterior-palapa-roof-hammock-jungle.jpg"
mv "CASA CACTUS2025-005.jpg"  "room-detail-red-heliconia-green-vase-table.jpg"
mv "CASA CACTUS2025-006.jpg"  "room-detail-red-ginger-fern-green-vase-window.jpg"
mv "CASA CACTUS2025-007.jpg"  "apartment-kitchen-cabinet-open-dishes-pots-glassware.jpg"
mv "CASA CACTUS2025-008.jpg"  "apartment-kitchen-induction-hob-coffee-maker-counter.jpg"
mv "CASA CACTUS2025-009.jpg"  "apartment-bathroom-sliding-barn-door-concrete-sink.jpg"
mv "CASA CACTUS2025-010.jpg"  "apartment-bathroom-barn-door-sink-round-mirror-towels.jpg"
mv "CASA CACTUS2025-011.jpg"  "apartment-kitchen-shelf-bowls-plates-pans.jpg"
mv "CASA CACTUS2025-012.jpg"  "apartment-kitchen-drawer-red-silicone-utensils.jpg"
mv "CASA CACTUS2025-013.jpg"  "apartment-kitchen-drawer-wooden-knives-cutlery.jpg"
mv "CASA CACTUS2025-014.jpg"  "bungalow-bedroom-twin-beds-blue-pillows-sailboat-painting.jpg"
mv "CASA CACTUS2025-015.jpg"  "bungalow-bedroom-twin-beds-garden-window-banana-leaves.jpg"
mv "CASA CACTUS2025-016.jpg"  "bungalow-bedroom-twin-beds-frontal-wicker-pendants.jpg"
mv "CASA CACTUS2025-017.jpg"  "bathroom-stone-wall-round-mirror-carved-rock-sink-wide.jpg"
mv "CASA CACTUS2025-018.jpg"  "bathroom-stone-wall-toilet-carved-sink-wide.jpg"
mv "CASA CACTUS2025-019.jpg"  "bungalow-bathroom-glass-shower-stone-wall-stool.jpg"
mv "CASA CACTUS2025-020.jpg"  "bungalow-bathroom-open-shower-stone-wall-towels.jpg"
mv "CASA CACTUS2025-021.jpg"  "bungalow-bedroom-twin-beds-baby-cot-highchair.jpg"
mv "CASA CACTUS2025-022.jpg"  "bungalow-bedroom-baby-cot-garden-window.jpg"
mv "CASA CACTUS2025-023.jpg"  "bungalow-bedroom-baby-cot-close-up-wicker-pendant.jpg"
mv "CASA CACTUS2025-024.jpg"  "room-baby-highchair-family-friendly-amenity.jpg"
mv "CASA CACTUS2025-025.jpg"  "bungalow-bedroom-stone-wall-double-bed-yellow-accents-wide.jpg"
mv "CASA CACTUS2025-026.jpg"  "bungalow-bedroom-stone-wall-double-bed-wicker-pendants.jpg"
mv "CASA CACTUS2025-027.jpg"  "bungalow-bedroom-stone-wall-yellow-pillows-bathroom-door.jpg"
mv "CASA CACTUS2025-028.jpg"  "bungalow-bedroom-stone-wall-bed-bathroom-visible.jpg"
mv "CASA CACTUS2025-029.jpg"  "bungalow-room-wardrobe-sitting-table-garden-window.jpg"
mv "CASA CACTUS2025-030.jpg"  "bungalow-bedroom-two-garden-windows-terrace-door.jpg"
mv "CASA CACTUS2025-031.jpg"  "apartment-studio-blue-sofa-work-desk-hammock-balcony.jpg"
mv "CASA CACTUS2025-032.jpg"  "apartment-bedroom-yellow-pillows-sliding-barn-door.jpg"
mv "CASA CACTUS2025-033.jpg"  "apartment-studio-parrot-painting-blue-sofa-red-fridge.jpg"
mv "CASA CACTUS2025-034.jpg"  "apartment-kitchen-red-hisense-fridge-coffee-maker-cabinets.jpg"
mv "CASA CACTUS2025-035.jpg"  "apartment-hallway-kitchen-to-bedroom-balcony.jpg"
mv "CASA CACTUS2025-036.jpg"  "apartment-kitchen-corridor-wicker-pendant-garden.jpg"
mv "CASA CACTUS2025-037.jpg"  "apartment-living-area-desk-wicker-pendant-balcony-golden-light.jpg"
mv "CASA CACTUS2025-038.jpg"  "apartment-living-area-ceiling-fan-desk-open-balcony.jpg"
mv "CASA CACTUS2025-039.jpg"  "apartment-bedroom-blue-bed-parrot-painting-balcony-hammock.jpg"
mv "CASA CACTUS2025-040.jpg"  "apartment-living-blue-sofa-parrot-painting-open-bedroom.jpg"
mv "CASA CACTUS2025-041.jpg"  "apartment-studio-blue-bed-parrot-painting-ceiling-fan.jpg"
mv "CASA CACTUS2025-042.jpg"  "apartment-bedroom-yellow-accents-barn-door-ceiling-fan.jpg"
mv "CASA CACTUS2025-043.jpg"  "apartment-bedroom-yellow-closet-ceiling-fan-balcony.jpg"
mv "CASA CACTUS2025-044.jpg"  "apartment-bedroom-yellow-closet-side-view-balcony.jpg"
mv "CASA CACTUS2025-045.jpg"  "apartment-studio-blue-bed-balcony-hammock-open-garden.jpg"
mv "CASA CACTUS2025-046.jpg"  "apartment-studio-blue-bed-ceiling-fan-open-balcony.jpg"
mv "CASA CACTUS2025-047.jpg"  "apartment-bedroom-yellow-barn-door-ceiling-fan-window.jpg"
mv "CASA CACTUS2025-048.jpg"  "apartment-studio-blue-bed-parrot-kitchenette-bathroom.jpg"
mv "CASA CACTUS2025-049.jpg"  "garden-cactus-row-five-white-wall-stone-border.jpg"
mv "CASA CACTUS2025-050.jpg"  "founders-sebastian-and-jey-portrait-cactus-mosaic-wall.jpg"
mv "CASA CACTUS2025-051.jpg"  "founders-jey-and-sebastian-smiling-portrait-best.jpg"
mv "CASA CACTUS2025-052.jpg"  "room-sitting-area-round-table-blue-chairs-banana-window.jpg"
mv "CASA CACTUS2025-053.jpg"  "room-sitting-table-crochet-cactus-detail-garden-window.jpg"
mv "CASA CACTUS2025-054.jpg"  "room-wicker-pendant-lamp-warm-light-close-up.jpg"
mv "CASA CACTUS2025-055.jpg"  "bungalow-bedroom-twin-beds-sailboat-painting-wicker-pendants.jpg"
mv "CASA CACTUS2025-056.jpg"  "bathroom-amenities-shampoo-conditioner-stone-wall.jpg"
mv "CASA CACTUS2025-057.jpg"  "bathroom-golden-amber-carved-stone-sink-round-mirror.jpg"
mv "CASA CACTUS2025-058.jpg"  "room-sitting-table-two-chairs-garden-window-sunlight.jpg"
mv "CASA CACTUS2025-059.jpg"  "bathroom-carved-stone-sink-round-mirror-chrome-faucet.jpg"
mv "CASA CACTUS2025-060.jpg"  "bungalow-bedroom-stone-wall-pendant-lights-bench-frontal.jpg"
mv "CASA CACTUS2025-061.jpg"  "bungalow-room-round-table-two-chairs-garden-window-ac.jpg"
mv "CASA CACTUS2025-062.jpg"  "bungalow-room-mini-fridge-wooden-cabinet-mirror-crochet.jpg"
mv "CASA CACTUS2025-063.jpg"  "bathroom-round-mirror-amber-stone-sink-chrome-wallfaucet.jpg"
mv "CASA CACTUS2025-064.jpg"  "bungalow-room-round-table-red-ginger-window-closet.jpg"
mv "CASA CACTUS2025-065.jpg"  "apartment-work-desk-concrete-wicker-pendant-slit-window.jpg"
mv "CASA CACTUS2025-066.jpg"  "bungalow-bedroom-double-bed-yellow-accents-towels-folded.jpg"
mv "CASA CACTUS2025-067.jpg"  "stone-wall-bungalow-king-bed-frontal-wicker-pendants.jpg"
mv "CASA CACTUS2025-068.jpg"  "bungalow-room-wide-bed-table-chairs-shelving-fridge.jpg"
mv "CASA CACTUS2025-069.jpg"  "stone-wall-bungalow-private-terrace-hammock-equipal-chairs.jpg"
mv "CASA CACTUS2025-070.jpg"  "property-exterior-street-view-gate-open-cactus.jpg"
mv "CASA CACTUS2025-071.jpg"  "property-exterior-gate-closed-stone-wall-cactus-agave.jpg"
mv "CASA CACTUS2025-072.jpg"  "property-exterior-wider-gate-trees-street-approach.jpg"
mv "CASA CACTUS2025-073.jpg"  "property-exterior-woman-staircase-cactus-mosaic-wall.jpg"
mv "CASA CACTUS2025-074.jpg"  "property-exterior-cactus-staircase-mosaic-wall.jpg"
mv "CASA CACTUS2025-075.jpg"  "cactus-columnar-pink-fruit-mosaic-stone-wall-vertical.jpg"
mv "CASA CACTUS2025-076.jpg"  "cactus-top-pink-fruit-mosaic-wall-upward.jpg"
mv "CASA CACTUS2025-077.jpg"  "cactus-extreme-closeup-pink-fruit-spine-detail.jpg"
mv "CASA CACTUS2025-078.jpg"  "entrance-sign-wooden-doorbell-white-wall-shadow.jpg"
mv "CASA CACTUS2025-079.jpg"  "property-parking-sign-painted-wood-turquoise-banana.jpg"
mv "CASA CACTUS2025-080.jpg"  "garden-banana-tree-green-bunch-upward-blue-sky.jpg"
mv "CASA CACTUS2025-081.jpg"  "garden-banana-bunch-close-up-blue-sky.jpg"
mv "CASA CACTUS2025-082.jpg"  "garden-cactus-row-mosaic-wall-path-banana-palms.jpg"
mv "CASA CACTUS2025-083.jpg"  "garden-chili-pepper-bush-red-chilies-palapa.jpg"
mv "CASA CACTUS2025-084.jpg"  "garden-chili-pepper-closeup-red-green.jpg"
mv "CASA CACTUS2025-085.jpg"  "garden-white-oleander-sunflare-bungalow-golden-light.jpg"
mv "CASA CACTUS2025-086.jpg"  "property-sign-this-must-be-the-place-casa-cactus.jpg"
mv "CASA CACTUS2025-087.jpg"  "pool-area-outdoor-wc-sink-rattan-mirror-wooden-door.jpg"
mv "CASA CACTUS2025-088.jpg"  "pool-area-wc-door-garden-foliage-pink-flowers.jpg"
mv "CASA CACTUS2025-089.jpg"  "pool-curved-steps-palm-tree-lush-garden-ground.jpg"
mv "CASA CACTUS2025-090.jpg"  "bungalow-terrace-palapa-hammock-equipal-chairs-wicker-lit.jpg"
mv "CASA CACTUS2025-091.jpg"  "bungalow-1-terrace-through-vines-hammock-number-sign.jpg"
mv "CASA CACTUS2025-092.jpg"  "garden-tree-swing-blue-rope-monstera-palapa-terrace.jpg"
mv "CASA CACTUS2025-093.jpg"  "garden-path-curved-pool-string-lights-loungers-red-ginger.jpg"
mv "CASA CACTUS2025-094.jpg"  "garden-path-curved-pool-string-lights-wider.jpg"
mv "CASA CACTUS2025-095.jpg"  "mari-poolside-reading-feet-in-water-palm-stone-wall.jpg"
mv "CASA CACTUS2025-096.jpg"  "lifestyle-reading-book-poolside-lime-drink-overhead.jpg"
mv "CASA CACTUS2025-097.jpg"  "mari-portrait-sun-lounger-book-lime-drink-bungalow.jpg"
mv "CASA CACTUS2025-098.jpg"  "lifestyle-reading-book-lime-drink-garden-pool-behind.jpg"
mv "CASA CACTUS2025-099.jpg"  "pool-palapa-dining-terrace-freeform-garden-wide.jpg"
mv "CASA CACTUS2025-100.jpg"  "pool-under-tree-palapa-dining-terrace-garden.jpg"
mv "CASA CACTUS2025-101.jpg"  "garden-path-woman-white-dress-walking-lifestyle.jpg"
mv "CASA CACTUS2025-102.jpg"  "garden-path-woman-white-dress-wider-apartment.jpg"
mv "CASA CACTUS2025-103.jpg"  "pool-elevated-palapa-dining-from-balcony.jpg"
mv "CASA CACTUS2025-104.jpg"  "pool-elevated-freeform-wider-from-balcony.jpg"
mv "CASA CACTUS2025-105.jpg"  "property-back-entrance-stone-wall-coconut-palm-vines.jpg"
mv "CASA CACTUS2025-106.jpg"  "property-entrance-casa-cactus-terracotta-sign-stone-wall.jpg"
mv "CASA CACTUS2025-107.jpg"  "apartment-studio-blue-bed-work-desk-balcony-hammock-wide.jpg"
mv "CASA CACTUS2025-108.jpg"  "apartment-studio-parrot-painting-red-fridge-kitchenette-wide.jpg"
mv "CASA CACTUS2025-109.jpg"  "pool-drone-overhead-freeform-shape-steps-clean.jpg"
mv "CASA CACTUS2025-110.jpg"  "aerial-buenavista-village-laguna-no-pin.jpg"
mv "CASA CACTUS2025-111.jpg"  "aerial-buenavista-laguna-wider-angle.jpg"
mv "CASA CACTUS2025-112.jpg"  "pool-aerial-loungers-garden-palms-steps.jpg"
mv "CASA CACTUS2025-113.jpg"  "pool-aerial-freeform-shape-terrace-overhead.jpg"

# ── CAT PHOTOS (uploaded separately with UUID filenames) ─────────────────────
# Run these manually from wherever the UUID files are located:
mv "dac4fae5-9d71-4314-9cbb-63c761f0f0e7.jpg"  "mimish-white-cat-sleeping-garden.jpg"
mv "93f021ef-f041-48c2-ba1e-4d3f0764bd5f.jpg"   "mimish-white-cat-squinting-garden.jpg"
mv "1a06fcda-f861-4b86-89c3-a5a0fb5238bb.jpg"   "chiku-tabby-cat-sun-lounger-wide.jpg"
mv "a1846f91-5bd4-4e94-a9f0-7a24d6eb4a3c.jpg"   "chiku-tabby-cat-sun-lounger-portrait.jpg"

echo "Done. All $(ls *.jpg 2>/dev/null | wc -l) images renamed."